name: Update Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-readme-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Generate readme stats card
        # uses: readme-tools/github-readme-stats-action@b4d2ef3b8051484b318d455163153b23a2b35fa2 # v1.1.0
        uses: hyperfinitism/github-readme-stats-action@1af0253a90914e782980ad25e9197ec4f7eefe8c
        with:
          card: stats
          options: >-
            {
              "username": "${{ github.repository_owner }}",
              "theme": "transparent",
              "show_icons": true,
              "show": "prs_merged"
            }
          path: assets/stats/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate top languages card
        # uses: readme-tools/github-readme-stats-action@b4d2ef3b8051484b318d455163153b23a2b35fa2 # v1.1.0
        uses: hyperfinitism/github-readme-stats-action@1af0253a90914e782980ad25e9197ec4f7eefe8c
        with:
          card: top-langs
          options: >-
            {
              "username": "${{ github.repository_owner }}",
              "layout": "donut",
              "theme": "transparent",
              "langs_count": 5
            }
          path: assets/stats/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload stat cards
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: cards-stats
          path: assets/stats/*.svg
  generate-repository-pins:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - repo: rust-tpm2-cli
            owner: hyperfinitism
          - repo: enact-rs
            owner: hyperfinitism
          - repo: ortho
            owner: hyperfinitism
          - repo: ima-parser
            owner: hyperfinitism
          - repo: gh-contrib-stats
            owner: hyperfinitism
          - repo: license-logic
            owner: hyperfinitism
    steps:
      - name: Generate pin card for ${{ matrix.owner }}/${{ matrix.repo }}
        # uses: readme-tools/github-readme-stats-action@b4d2ef3b8051484b318d455163153b23a2b35fa2 # v1.1.0
        uses: hyperfinitism/github-readme-stats-action@1af0253a90914e782980ad25e9197ec4f7eefe8c
        with:
          card: pin
          options: >-
            {
              "username": "${{ matrix.owner }}",
              "repo": "${{ matrix.repo }}",
              "theme": "transparent"
            }
          path: assets/pins/${{ matrix.owner }}-${{ matrix.repo }}.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload pin card
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: cards-pin-${{ matrix.owner }}-${{ matrix.repo }}
          path: assets/pins/*.svg
  commit-cards:
    needs: [generate-readme-stats, generate-repository-pins]
    if: ${{ !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Download stat cards
        if: ${{ needs.generate-readme-stats.result == 'success' }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: cards-stats
          path: assets/stats
      - name: Download pin cards
        if: ${{ needs.generate-repository-pins.result == 'success' }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: cards-pin-*
          path: assets/pins
          merge-multiple: true

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/
          git commit -m "assets: Update README cards" --signoff || exit 0
          git push
